#ifndef LOGGER_OUTPUT_STD
#define LOGGER_OUTPUT_STD(...)
#endif

#if PIXIE_OUTPUT_TYPE == PIXIE_OUTPUT_TYPE_game

LOGGER_OUTPUT_STD(console)
LOGGER_OUTPUT_STD(data)

#elif PIXIE_OUTPUT_TYPE == PIXIE_OUTPUT_TYPE_editor

LOGGER_OUTPUT_STD(console)
LOGGER_OUTPUT_STD(data)

#elif PIXIE_OUTPUT_TYPE == PIXIE_OUTPUT_TYPE_launcher

LOGGER_OUTPUT_STD(console)
LOGGER_OUTPUT_STD(data)

#endif

#undef LOGGER_OUTPUT_STD