#!/bin/sh

echo Starting up…
if [ -z "$1" ]
  then
    cd "$(dirname "$0")"
  else
    cd "$(dirname "$1")"
fi

if [ -d "./_engine/depedency" ]; then

	cd ./_engine/build/doxygen

	if [ -f ../../docs/index.html ]; then
		chmod +x ./view_docs
		./view_docs
	else

	echo "Documentation does not exists, regeneraing now... Please allow a few seconds to complete"
	   
		chmod +x ./generate_docs
		chmod +x ./view_docs
		./generate_docs
		./view_docs

	fi
	
else
  
	echo "Use download_dependencies to download required depedencies before doing anything else!"

fi