#!/bin/sh

if [ -z "$1" ]
  then
    cd "$(dirname "$0")"
  else
    cd "$1"
fi

if [ -d "./engine/depedency" ]; then
   
echo "Use download_dependencies to download required depedencies before doing anything else!"

else

cd ./_engine/build/doxygen

if [ -f ../../docs/index.html ]; then
    ./view_docs
else

echo "Documentation does not exists, regeneraing now... Please allow a few seconds to complete"

    ./generate_docs
    ./view_docs

fi

fi