#!/bin/sh
echo Starting up…
if [ -z "$1" ]
  then
    cd "$(dirname "$0")"
  else
    cd "$(dirname "$1")"
fi
cd _engine/build/dependency
chmod +x ./download
chmod +x ./pack_and_upload

OS="`uname`"
if [ $OS  == "Darwin" ]
  then
    echo Follow instructions in separate window
    echo You can close this window afterwards
    open ./download
  else
    ./download
fi
