#ifndef ENGINE_COMMON_UTILITY_PATTERN_ENUM_HPP
#define ENGINE_COMMON_UTILITY_PATTERN_ENUM_HPP
#pragma once

#include <unordered_map>
#include <bitset>
#include <type_traits>

namespace engine
{

	/**
	 * @brief Converts any strongly-typed enum value into its underlying type
	 * 
	 * @tparam enum_t Enum type
	 * @param[in] val Enum value
	 * @return Value converted to underlying type 
	 */
	template<class enum_t> constexpr auto value_of(enum_t val) -> typename std::underlying_type<enum_t>::type
	{
		return static_cast<typename std::underlying_type<enum_t>::type>(val);
	}

}

#define ENUM_NAME(name, ...) name
#define ENUM_VALUE_1(name) #name##_u
#define ENUM_VALUE_2(name, str) str##_u
#define ENUM_VALUE_3(name, str, value) str##_u

#define EXPAND_MULTI(...) __VA_ARGS__
#define _GET_NTH_ARG3(_1, _2, _3, N, ...) N
#define _GET_NTH_ARG3_INT(...) EXPAND(_GET_NTH_ARG3(__VA_ARGS__))

#define ENUM_PROVIDER_0() 
#define ENUM_PROVIDER_1(provider_type, p1) case provider_type::ENUM_NAME p1: return EXPAND(EXPAND(_GET_NTH_ARG3_INT(EXPAND_MULTI p1, ENUM_VALUE_3, ENUM_VALUE_2,  ENUM_VALUE_1)) p1);
#define ENUM_PROVIDER_2(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_1(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_3(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_2(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_4(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_3(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_5(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_4(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_6(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_5(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_7(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_6(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_8(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_7(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_9(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_8(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_10(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_9(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_11(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_10(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_12(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_11(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_13(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_12(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_14(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_13(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_15(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_14(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_16(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_15(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_17(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_16(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_18(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_17(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_19(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_18(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_20(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_19(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_21(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_20(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_22(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_21(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_23(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_22(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_24(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_23(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_25(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_24(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_26(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_25(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_27(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_26(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_28(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_27(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_29(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_28(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_30(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_29(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_31(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_30(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_32(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_31(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_33(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_32(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_34(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_33(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_35(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_34(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_36(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_35(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_37(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_36(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_38(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_37(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_39(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_38(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_40(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_39(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_41(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_40(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_42(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_41(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_43(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_42(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_44(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_43(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_45(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_44(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_46(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_45(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_47(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_46(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_48(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_47(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_49(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_48(provider_type, __VA_ARGS__))
#define ENUM_PROVIDER_50(provider_type, p1, ...) ENUM_PROVIDER_1(provider_type, p1) EXPAND(ENUM_PROVIDER_49(provider_type, __VA_ARGS__))

#define ENUM_REVERSE_PROVIDER_0() 
#define ENUM_REVERSE_PROVIDER_1(provider_type, p1) if(EXPAND(EXPAND(_GET_NTH_ARG3_INT(EXPAND_MULTI p1, ENUM_VALUE_3, ENUM_VALUE_2,  ENUM_VALUE_1)) p1) == str) return provider_type::ENUM_NAME p1 ;
#define ENUM_REVERSE_PROVIDER_2(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_1(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_3(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_2(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_4(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_3(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_5(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_4(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_6(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_5(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_7(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_6(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_8(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_7(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_9(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_8(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_10(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_9(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_11(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_10(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_12(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_11(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_13(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_12(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_14(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_13(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_15(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_14(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_16(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_15(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_17(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_16(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_18(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_17(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_19(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_18(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_20(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_19(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_21(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_20(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_22(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_21(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_23(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_22(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_24(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_23(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_25(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_24(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_26(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_25(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_27(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_26(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_28(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_27(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_29(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_28(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_30(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_29(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_31(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_30(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_32(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_31(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_33(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_32(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_34(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_33(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_35(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_34(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_36(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_35(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_37(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_36(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_38(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_37(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_39(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_38(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_40(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_39(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_41(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_40(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_42(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_41(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_43(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_42(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_44(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_43(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_45(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_44(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_46(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_45(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_47(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_46(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_48(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_47(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_49(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_48(provider_type, __VA_ARGS__))
#define ENUM_REVERSE_PROVIDER_50(provider_type, p1, ...) ENUM_REVERSE_PROVIDER_1(provider_type, p1) EXPAND(ENUM_REVERSE_PROVIDER_49(provider_type, __VA_ARGS__))

#define ENUM_ITEM_0() 
#define ENUM_ITEM_1(provider_type, p1) ENUM_NAME p1
#define ENUM_ITEM_2(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_1(provider_type, __VA_ARGS__))
#define ENUM_ITEM_3(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_2(provider_type, __VA_ARGS__))
#define ENUM_ITEM_4(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_3(provider_type, __VA_ARGS__))
#define ENUM_ITEM_5(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_4(provider_type, __VA_ARGS__))
#define ENUM_ITEM_6(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_5(provider_type, __VA_ARGS__))
#define ENUM_ITEM_7(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_6(provider_type, __VA_ARGS__))
#define ENUM_ITEM_8(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_7(provider_type, __VA_ARGS__))
#define ENUM_ITEM_9(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_8(provider_type, __VA_ARGS__))
#define ENUM_ITEM_10(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_9(provider_type, __VA_ARGS__))
#define ENUM_ITEM_11(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_10(provider_type, __VA_ARGS__))
#define ENUM_ITEM_12(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_11(provider_type, __VA_ARGS__))
#define ENUM_ITEM_13(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_12(provider_type, __VA_ARGS__))
#define ENUM_ITEM_14(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_13(provider_type, __VA_ARGS__))
#define ENUM_ITEM_15(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_14(provider_type, __VA_ARGS__))
#define ENUM_ITEM_16(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_15(provider_type, __VA_ARGS__))
#define ENUM_ITEM_17(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_16(provider_type, __VA_ARGS__))
#define ENUM_ITEM_18(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_17(provider_type, __VA_ARGS__))
#define ENUM_ITEM_19(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_18(provider_type, __VA_ARGS__))
#define ENUM_ITEM_20(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_19(provider_type, __VA_ARGS__))
#define ENUM_ITEM_21(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_20(provider_type, __VA_ARGS__))
#define ENUM_ITEM_22(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_21(provider_type, __VA_ARGS__))
#define ENUM_ITEM_23(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_22(provider_type, __VA_ARGS__))
#define ENUM_ITEM_24(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_23(provider_type, __VA_ARGS__))
#define ENUM_ITEM_25(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_24(provider_type, __VA_ARGS__))
#define ENUM_ITEM_26(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_25(provider_type, __VA_ARGS__))
#define ENUM_ITEM_27(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_26(provider_type, __VA_ARGS__))
#define ENUM_ITEM_28(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_27(provider_type, __VA_ARGS__))
#define ENUM_ITEM_29(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_28(provider_type, __VA_ARGS__))
#define ENUM_ITEM_30(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_29(provider_type, __VA_ARGS__))
#define ENUM_ITEM_31(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_30(provider_type, __VA_ARGS__))
#define ENUM_ITEM_32(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_31(provider_type, __VA_ARGS__))
#define ENUM_ITEM_33(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_32(provider_type, __VA_ARGS__))
#define ENUM_ITEM_34(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_33(provider_type, __VA_ARGS__))
#define ENUM_ITEM_35(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_34(provider_type, __VA_ARGS__))
#define ENUM_ITEM_36(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_35(provider_type, __VA_ARGS__))
#define ENUM_ITEM_37(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_36(provider_type, __VA_ARGS__))
#define ENUM_ITEM_38(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_37(provider_type, __VA_ARGS__))
#define ENUM_ITEM_39(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_38(provider_type, __VA_ARGS__))
#define ENUM_ITEM_40(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_39(provider_type, __VA_ARGS__))
#define ENUM_ITEM_41(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_40(provider_type, __VA_ARGS__))
#define ENUM_ITEM_42(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_41(provider_type, __VA_ARGS__))
#define ENUM_ITEM_43(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_42(provider_type, __VA_ARGS__))
#define ENUM_ITEM_44(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_43(provider_type, __VA_ARGS__))
#define ENUM_ITEM_45(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_44(provider_type, __VA_ARGS__))
#define ENUM_ITEM_46(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_45(provider_type, __VA_ARGS__))
#define ENUM_ITEM_47(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_46(provider_type, __VA_ARGS__))
#define ENUM_ITEM_48(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_47(provider_type, __VA_ARGS__))
#define ENUM_ITEM_49(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_48(provider_type, __VA_ARGS__))
#define ENUM_ITEM_50(provider_type, p1, ...) ENUM_ITEM_1(provider_type, p1), EXPAND(ENUM_ITEM_49(provider_type, __VA_ARGS__))

#define EXPAND( x ) x
#define _GET_NTH_ARG50(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, N, ...) N

#define DEFINE_ENUM_TYPE(name, ...) enum class name { EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ITEM_50, ENUM_ITEM_49, ENUM_ITEM_48, ENUM_ITEM_47, ENUM_ITEM_46, ENUM_ITEM_45, ENUM_ITEM_44, ENUM_ITEM_43, ENUM_ITEM_42, ENUM_ITEM_41, ENUM_ITEM_40, ENUM_ITEM_39, ENUM_ITEM_38, ENUM_ITEM_37, ENUM_ITEM_36, ENUM_ITEM_35, ENUM_ITEM_34, ENUM_ITEM_33, ENUM_ITEM_32, ENUM_ITEM_31, ENUM_ITEM_30, ENUM_ITEM_29, ENUM_ITEM_28, ENUM_ITEM_27, ENUM_ITEM_26, ENUM_ITEM_25, ENUM_ITEM_24, ENUM_ITEM_23, ENUM_ITEM_22, ENUM_ITEM_21, ENUM_ITEM_20, ENUM_ITEM_19, ENUM_ITEM_18, ENUM_ITEM_17, ENUM_ITEM_16, ENUM_ITEM_15, ENUM_ITEM_14, ENUM_ITEM_13, ENUM_ITEM_12, ENUM_ITEM_11, ENUM_ITEM_10, ENUM_ITEM_9, ENUM_ITEM_8, ENUM_ITEM_7, ENUM_ITEM_6, ENUM_ITEM_5, ENUM_ITEM_4, ENUM_ITEM_3, ENUM_ITEM_2, ENUM_ITEM_1, ENUM_ITEM_0))(name, __VA_ARGS__)), count }; 
#define DEFINE_ENUM_TO_STRING(name, ...) namespace engine { template<> inline ustring_t to_string<name>(const name & item, const ustring_t & format) { switch(item) { EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_PROVIDER_50, ENUM_PROVIDER_49, ENUM_PROVIDER_48, ENUM_PROVIDER_47, ENUM_PROVIDER_46, ENUM_PROVIDER_45, ENUM_PROVIDER_44, ENUM_PROVIDER_43, ENUM_PROVIDER_42, ENUM_PROVIDER_41, ENUM_PROVIDER_40, ENUM_PROVIDER_39, ENUM_PROVIDER_38, ENUM_PROVIDER_37, ENUM_PROVIDER_36, ENUM_PROVIDER_35, ENUM_PROVIDER_34, ENUM_PROVIDER_33, ENUM_PROVIDER_32, ENUM_PROVIDER_31, ENUM_PROVIDER_30, ENUM_PROVIDER_29, ENUM_PROVIDER_28, ENUM_PROVIDER_27, ENUM_PROVIDER_26, ENUM_PROVIDER_25, ENUM_PROVIDER_24, ENUM_PROVIDER_23, ENUM_PROVIDER_22, ENUM_PROVIDER_21, ENUM_PROVIDER_20, ENUM_PROVIDER_19, ENUM_PROVIDER_18, ENUM_PROVIDER_17, ENUM_PROVIDER_16, ENUM_PROVIDER_15, ENUM_PROVIDER_14, ENUM_PROVIDER_13, ENUM_PROVIDER_12, ENUM_PROVIDER_11, ENUM_PROVIDER_10, ENUM_PROVIDER_9, ENUM_PROVIDER_8, ENUM_PROVIDER_7, ENUM_PROVIDER_6, ENUM_PROVIDER_5, ENUM_PROVIDER_4, ENUM_PROVIDER_3, ENUM_PROVIDER_2, ENUM_PROVIDER_1, ENUM_PROVIDER_0))(name, __VA_ARGS__)) } return "Unknown"_u; } template<> inline name from_string<name>(const ustring_t & str) { EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_REVERSE_PROVIDER_50, ENUM_REVERSE_PROVIDER_49, ENUM_REVERSE_PROVIDER_48, ENUM_REVERSE_PROVIDER_47, ENUM_REVERSE_PROVIDER_46, ENUM_REVERSE_PROVIDER_45, ENUM_REVERSE_PROVIDER_44, ENUM_REVERSE_PROVIDER_43, ENUM_REVERSE_PROVIDER_42, ENUM_REVERSE_PROVIDER_41, ENUM_REVERSE_PROVIDER_40, ENUM_REVERSE_PROVIDER_39, ENUM_REVERSE_PROVIDER_38, ENUM_REVERSE_PROVIDER_37, ENUM_REVERSE_PROVIDER_36, ENUM_REVERSE_PROVIDER_35, ENUM_REVERSE_PROVIDER_34, ENUM_REVERSE_PROVIDER_33, ENUM_REVERSE_PROVIDER_32, ENUM_REVERSE_PROVIDER_31, ENUM_REVERSE_PROVIDER_30, ENUM_REVERSE_PROVIDER_29, ENUM_REVERSE_PROVIDER_28, ENUM_REVERSE_PROVIDER_27, ENUM_REVERSE_PROVIDER_26, ENUM_REVERSE_PROVIDER_25, ENUM_REVERSE_PROVIDER_24, ENUM_REVERSE_PROVIDER_23, ENUM_REVERSE_PROVIDER_22, ENUM_REVERSE_PROVIDER_21, ENUM_REVERSE_PROVIDER_20, ENUM_REVERSE_PROVIDER_19, ENUM_REVERSE_PROVIDER_18, ENUM_REVERSE_PROVIDER_17, ENUM_REVERSE_PROVIDER_16, ENUM_REVERSE_PROVIDER_15, ENUM_REVERSE_PROVIDER_14, ENUM_REVERSE_PROVIDER_13, ENUM_REVERSE_PROVIDER_12, ENUM_REVERSE_PROVIDER_11, ENUM_REVERSE_PROVIDER_10, ENUM_REVERSE_PROVIDER_9, ENUM_REVERSE_PROVIDER_8, ENUM_REVERSE_PROVIDER_7, ENUM_REVERSE_PROVIDER_6, ENUM_REVERSE_PROVIDER_5, ENUM_REVERSE_PROVIDER_4, ENUM_REVERSE_PROVIDER_3, ENUM_REVERSE_PROVIDER_2, ENUM_REVERSE_PROVIDER_1, ENUM_REVERSE_PROVIDER_0))(name, __VA_ARGS__)) return name::count; } }

#define ENUM_EXTRACT_1ST(name, ...) name

#define ENUM_ONLY_1ST_0() 
#define ENUM_ONLY_1ST_1(provider_type, p1) (EXPAND(ENUM_EXTRACT_1ST p1))
#define ENUM_ONLY_1ST_2(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_1(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_3(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_2(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_4(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_3(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_5(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_4(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_6(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_5(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_7(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_6(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_8(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_7(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_9(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_8(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_10(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_9(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_11(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_10(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_12(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_11(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_13(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_12(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_14(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_13(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_15(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_14(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_16(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_15(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_17(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_16(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_18(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_17(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_19(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_18(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_20(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_19(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_21(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_20(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_22(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_21(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_23(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_22(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_24(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_23(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_25(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_24(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_26(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_25(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_27(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_26(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_28(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_27(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_29(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_28(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_30(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_29(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_31(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_30(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_32(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_31(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_33(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_32(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_34(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_33(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_35(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_34(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_36(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_35(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_37(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_36(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_38(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_37(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_39(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_38(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_40(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_39(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_41(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_40(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_42(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_41(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_43(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_42(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_44(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_43(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_45(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_44(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_46(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_45(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_47(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_46(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_48(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_47(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_49(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_48(provider_type, __VA_ARGS__))
#define ENUM_ONLY_1ST_50(provider_type, p1, ...) ENUM_ONLY_1ST_1(provider_type, p1), EXPAND(ENUM_ONLY_1ST_49(provider_type, __VA_ARGS__))

#define DEFINE_ENUM_ONLY_1ST_TYPE(name, ...) DEFINE_ENUM_TYPE(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_1ST_50, ENUM_ONLY_1ST_49, ENUM_ONLY_1ST_48, ENUM_ONLY_1ST_47, ENUM_ONLY_1ST_46, ENUM_ONLY_1ST_45, ENUM_ONLY_1ST_44, ENUM_ONLY_1ST_43, ENUM_ONLY_1ST_42, ENUM_ONLY_1ST_41, ENUM_ONLY_1ST_40, ENUM_ONLY_1ST_39, ENUM_ONLY_1ST_38, ENUM_ONLY_1ST_37, ENUM_ONLY_1ST_36, ENUM_ONLY_1ST_35, ENUM_ONLY_1ST_34, ENUM_ONLY_1ST_33, ENUM_ONLY_1ST_32, ENUM_ONLY_1ST_31, ENUM_ONLY_1ST_30, ENUM_ONLY_1ST_29, ENUM_ONLY_1ST_28, ENUM_ONLY_1ST_27, ENUM_ONLY_1ST_26, ENUM_ONLY_1ST_25, ENUM_ONLY_1ST_24, ENUM_ONLY_1ST_23, ENUM_ONLY_1ST_22, ENUM_ONLY_1ST_21, ENUM_ONLY_1ST_20, ENUM_ONLY_1ST_19, ENUM_ONLY_1ST_18, ENUM_ONLY_1ST_17, ENUM_ONLY_1ST_16, ENUM_ONLY_1ST_15, ENUM_ONLY_1ST_14, ENUM_ONLY_1ST_13, ENUM_ONLY_1ST_12, ENUM_ONLY_1ST_11, ENUM_ONLY_1ST_10, ENUM_ONLY_1ST_9, ENUM_ONLY_1ST_8, ENUM_ONLY_1ST_7, ENUM_ONLY_1ST_6, ENUM_ONLY_1ST_5, ENUM_ONLY_1ST_4, ENUM_ONLY_1ST_3, ENUM_ONLY_1ST_2, ENUM_ONLY_1ST_1, ENUM_ONLY_1ST_0))(name, __VA_ARGS__)))
#define DEFINE_ENUM_ONLY_1ST_TO_STRING(name, ...) DEFINE_ENUM_TO_STRING(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_1ST_50, ENUM_ONLY_1ST_49, ENUM_ONLY_1ST_48, ENUM_ONLY_1ST_47, ENUM_ONLY_1ST_46, ENUM_ONLY_1ST_45, ENUM_ONLY_1ST_44, ENUM_ONLY_1ST_43, ENUM_ONLY_1ST_42, ENUM_ONLY_1ST_41, ENUM_ONLY_1ST_40, ENUM_ONLY_1ST_39, ENUM_ONLY_1ST_38, ENUM_ONLY_1ST_37, ENUM_ONLY_1ST_36, ENUM_ONLY_1ST_35, ENUM_ONLY_1ST_34, ENUM_ONLY_1ST_33, ENUM_ONLY_1ST_32, ENUM_ONLY_1ST_31, ENUM_ONLY_1ST_30, ENUM_ONLY_1ST_29, ENUM_ONLY_1ST_28, ENUM_ONLY_1ST_27, ENUM_ONLY_1ST_26, ENUM_ONLY_1ST_25, ENUM_ONLY_1ST_24, ENUM_ONLY_1ST_23, ENUM_ONLY_1ST_22, ENUM_ONLY_1ST_21, ENUM_ONLY_1ST_20, ENUM_ONLY_1ST_19, ENUM_ONLY_1ST_18, ENUM_ONLY_1ST_17, ENUM_ONLY_1ST_16, ENUM_ONLY_1ST_15, ENUM_ONLY_1ST_14, ENUM_ONLY_1ST_13, ENUM_ONLY_1ST_12, ENUM_ONLY_1ST_11, ENUM_ONLY_1ST_10, ENUM_ONLY_1ST_9, ENUM_ONLY_1ST_8, ENUM_ONLY_1ST_7, ENUM_ONLY_1ST_6, ENUM_ONLY_1ST_5, ENUM_ONLY_1ST_4, ENUM_ONLY_1ST_3, ENUM_ONLY_1ST_2, ENUM_ONLY_1ST_1, ENUM_ONLY_1ST_0))(name, __VA_ARGS__)))
#define DEFINE_ENUM_ONLY_1ST(name, ...) DEFINE_ENUM(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_1ST_50, ENUM_ONLY_1ST_49, ENUM_ONLY_1ST_48, ENUM_ONLY_1ST_47, ENUM_ONLY_1ST_46, ENUM_ONLY_1ST_45, ENUM_ONLY_1ST_44, ENUM_ONLY_1ST_43, ENUM_ONLY_1ST_42, ENUM_ONLY_1ST_41, ENUM_ONLY_1ST_40, ENUM_ONLY_1ST_39, ENUM_ONLY_1ST_38, ENUM_ONLY_1ST_37, ENUM_ONLY_1ST_36, ENUM_ONLY_1ST_35, ENUM_ONLY_1ST_34, ENUM_ONLY_1ST_33, ENUM_ONLY_1ST_32, ENUM_ONLY_1ST_31, ENUM_ONLY_1ST_30, ENUM_ONLY_1ST_29, ENUM_ONLY_1ST_28, ENUM_ONLY_1ST_27, ENUM_ONLY_1ST_26, ENUM_ONLY_1ST_25, ENUM_ONLY_1ST_24, ENUM_ONLY_1ST_23, ENUM_ONLY_1ST_22, ENUM_ONLY_1ST_21, ENUM_ONLY_1ST_20, ENUM_ONLY_1ST_19, ENUM_ONLY_1ST_18, ENUM_ONLY_1ST_17, ENUM_ONLY_1ST_16, ENUM_ONLY_1ST_15, ENUM_ONLY_1ST_14, ENUM_ONLY_1ST_13, ENUM_ONLY_1ST_12, ENUM_ONLY_1ST_11, ENUM_ONLY_1ST_10, ENUM_ONLY_1ST_9, ENUM_ONLY_1ST_8, ENUM_ONLY_1ST_7, ENUM_ONLY_1ST_6, ENUM_ONLY_1ST_5, ENUM_ONLY_1ST_4, ENUM_ONLY_1ST_3, ENUM_ONLY_1ST_2, ENUM_ONLY_1ST_1, ENUM_ONLY_1ST_0))(name, __VA_ARGS__)))

#define ENUM_EXTRACT_2ND(name, string, ...) name, string

#define ENUM_ONLY_2ND_0() 
#define ENUM_ONLY_2ND_1(provider_type, p1) (EXPAND(ENUM_EXTRACT_2ND p1))
#define ENUM_ONLY_2ND_2(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_1(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_3(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_2(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_4(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_3(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_5(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_4(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_6(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_5(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_7(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_6(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_8(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_7(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_9(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_8(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_10(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_9(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_11(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_10(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_12(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_11(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_13(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_12(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_14(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_13(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_15(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_14(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_16(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_15(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_17(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_16(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_18(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_17(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_19(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_18(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_20(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_19(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_21(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_20(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_22(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_21(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_23(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_22(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_24(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_23(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_25(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_24(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_26(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_25(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_27(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_26(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_28(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_27(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_29(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_28(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_30(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_29(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_31(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_30(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_32(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_31(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_33(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_32(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_34(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_33(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_35(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_34(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_36(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_35(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_37(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_36(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_38(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_37(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_39(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_38(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_40(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_39(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_41(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_40(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_42(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_41(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_43(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_42(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_44(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_43(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_45(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_44(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_46(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_45(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_47(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_46(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_48(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_47(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_49(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_48(provider_type, __VA_ARGS__))
#define ENUM_ONLY_2ND_50(provider_type, p1, ...) ENUM_ONLY_2ND_1(provider_type, p1), EXPAND(ENUM_ONLY_2ND_49(provider_type, __VA_ARGS__))

#define DEFINE_ENUM_ONLY_2ND_TYPE(name, ...) DEFINE_ENUM_TYPE(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_2ND_50, ENUM_ONLY_2ND_49, ENUM_ONLY_2ND_48, ENUM_ONLY_2ND_47, ENUM_ONLY_2ND_46, ENUM_ONLY_2ND_45, ENUM_ONLY_2ND_44, ENUM_ONLY_2ND_43, ENUM_ONLY_2ND_42, ENUM_ONLY_2ND_41, ENUM_ONLY_2ND_40, ENUM_ONLY_2ND_39, ENUM_ONLY_2ND_38, ENUM_ONLY_2ND_37, ENUM_ONLY_2ND_36, ENUM_ONLY_2ND_35, ENUM_ONLY_2ND_34, ENUM_ONLY_2ND_33, ENUM_ONLY_2ND_32, ENUM_ONLY_2ND_31, ENUM_ONLY_2ND_30, ENUM_ONLY_2ND_29, ENUM_ONLY_2ND_28, ENUM_ONLY_2ND_27, ENUM_ONLY_2ND_26, ENUM_ONLY_2ND_25, ENUM_ONLY_2ND_24, ENUM_ONLY_2ND_23, ENUM_ONLY_2ND_22, ENUM_ONLY_2ND_21, ENUM_ONLY_2ND_20, ENUM_ONLY_2ND_19, ENUM_ONLY_2ND_18, ENUM_ONLY_2ND_17, ENUM_ONLY_2ND_16, ENUM_ONLY_2ND_15, ENUM_ONLY_2ND_14, ENUM_ONLY_2ND_13, ENUM_ONLY_2ND_12, ENUM_ONLY_2ND_11, ENUM_ONLY_2ND_10, ENUM_ONLY_2ND_9, ENUM_ONLY_2ND_8, ENUM_ONLY_2ND_7, ENUM_ONLY_2ND_6, ENUM_ONLY_2ND_5, ENUM_ONLY_2ND_4, ENUM_ONLY_2ND_3, ENUM_ONLY_2ND_2, ENUM_ONLY_2ND_1, ENUM_ONLY_2ND_0))(name, __VA_ARGS__)))
#define DEFINE_ENUM_ONLY_2ND_TO_STRING(name, ...) DEFINE_ENUM_TO_STRING(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_2ND_50, ENUM_ONLY_2ND_49, ENUM_ONLY_2ND_48, ENUM_ONLY_2ND_47, ENUM_ONLY_2ND_46, ENUM_ONLY_2ND_45, ENUM_ONLY_2ND_44, ENUM_ONLY_2ND_43, ENUM_ONLY_2ND_42, ENUM_ONLY_2ND_41, ENUM_ONLY_2ND_40, ENUM_ONLY_2ND_39, ENUM_ONLY_2ND_38, ENUM_ONLY_2ND_37, ENUM_ONLY_2ND_36, ENUM_ONLY_2ND_35, ENUM_ONLY_2ND_34, ENUM_ONLY_2ND_33, ENUM_ONLY_2ND_32, ENUM_ONLY_2ND_31, ENUM_ONLY_2ND_30, ENUM_ONLY_2ND_29, ENUM_ONLY_2ND_28, ENUM_ONLY_2ND_27, ENUM_ONLY_2ND_26, ENUM_ONLY_2ND_25, ENUM_ONLY_2ND_24, ENUM_ONLY_2ND_23, ENUM_ONLY_2ND_22, ENUM_ONLY_2ND_21, ENUM_ONLY_2ND_20, ENUM_ONLY_2ND_19, ENUM_ONLY_2ND_18, ENUM_ONLY_2ND_17, ENUM_ONLY_2ND_16, ENUM_ONLY_2ND_15, ENUM_ONLY_2ND_14, ENUM_ONLY_2ND_13, ENUM_ONLY_2ND_12, ENUM_ONLY_2ND_11, ENUM_ONLY_2ND_10, ENUM_ONLY_2ND_9, ENUM_ONLY_2ND_8, ENUM_ONLY_2ND_7, ENUM_ONLY_2ND_6, ENUM_ONLY_2ND_5, ENUM_ONLY_2ND_4, ENUM_ONLY_2ND_3, ENUM_ONLY_2ND_2, ENUM_ONLY_2ND_1, ENUM_ONLY_2ND_0))(name, __VA_ARGS__)))
#define DEFINE_ENUM_ONLY_2ND(name, ...) DEFINE_ENUM(name, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, ENUM_ONLY_2ND_50, ENUM_ONLY_2ND_49, ENUM_ONLY_2ND_48, ENUM_ONLY_2ND_47, ENUM_ONLY_2ND_46, ENUM_ONLY_2ND_45, ENUM_ONLY_2ND_44, ENUM_ONLY_2ND_43, ENUM_ONLY_2ND_42, ENUM_ONLY_2ND_41, ENUM_ONLY_2ND_40, ENUM_ONLY_2ND_39, ENUM_ONLY_2ND_38, ENUM_ONLY_2ND_37, ENUM_ONLY_2ND_36, ENUM_ONLY_2ND_35, ENUM_ONLY_2ND_34, ENUM_ONLY_2ND_33, ENUM_ONLY_2ND_32, ENUM_ONLY_2ND_31, ENUM_ONLY_2ND_30, ENUM_ONLY_2ND_29, ENUM_ONLY_2ND_28, ENUM_ONLY_2ND_27, ENUM_ONLY_2ND_26, ENUM_ONLY_2ND_25, ENUM_ONLY_2ND_24, ENUM_ONLY_2ND_23, ENUM_ONLY_2ND_22, ENUM_ONLY_2ND_21, ENUM_ONLY_2ND_20, ENUM_ONLY_2ND_19, ENUM_ONLY_2ND_18, ENUM_ONLY_2ND_17, ENUM_ONLY_2ND_16, ENUM_ONLY_2ND_15, ENUM_ONLY_2ND_14, ENUM_ONLY_2ND_13, ENUM_ONLY_2ND_12, ENUM_ONLY_2ND_11, ENUM_ONLY_2ND_10, ENUM_ONLY_2ND_9, ENUM_ONLY_2ND_8, ENUM_ONLY_2ND_7, ENUM_ONLY_2ND_6, ENUM_ONLY_2ND_5, ENUM_ONLY_2ND_4, ENUM_ONLY_2ND_3, ENUM_ONLY_2ND_2, ENUM_ONLY_2ND_1, ENUM_ONLY_2ND_0))(name, __VA_ARGS__)))

#define TYPE_PASS_0() 
#define TYPE_PASS_1(provider_type, p1) provider_type p1
#define TYPE_PASS_2(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_1(provider_type, __VA_ARGS__))
#define TYPE_PASS_3(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_2(provider_type, __VA_ARGS__))
#define TYPE_PASS_4(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_3(provider_type, __VA_ARGS__))
#define TYPE_PASS_5(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_4(provider_type, __VA_ARGS__))
#define TYPE_PASS_6(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_5(provider_type, __VA_ARGS__))
#define TYPE_PASS_7(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_6(provider_type, __VA_ARGS__))
#define TYPE_PASS_8(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_7(provider_type, __VA_ARGS__))
#define TYPE_PASS_9(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_8(provider_type, __VA_ARGS__))
#define TYPE_PASS_10(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_9(provider_type, __VA_ARGS__))
#define TYPE_PASS_11(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_10(provider_type, __VA_ARGS__))
#define TYPE_PASS_12(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_11(provider_type, __VA_ARGS__))
#define TYPE_PASS_13(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_12(provider_type, __VA_ARGS__))
#define TYPE_PASS_14(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_13(provider_type, __VA_ARGS__))
#define TYPE_PASS_15(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_14(provider_type, __VA_ARGS__))
#define TYPE_PASS_16(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_15(provider_type, __VA_ARGS__))
#define TYPE_PASS_17(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_16(provider_type, __VA_ARGS__))
#define TYPE_PASS_18(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_17(provider_type, __VA_ARGS__))
#define TYPE_PASS_19(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_18(provider_type, __VA_ARGS__))
#define TYPE_PASS_20(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_19(provider_type, __VA_ARGS__))
#define TYPE_PASS_21(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_20(provider_type, __VA_ARGS__))
#define TYPE_PASS_22(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_21(provider_type, __VA_ARGS__))
#define TYPE_PASS_23(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_22(provider_type, __VA_ARGS__))
#define TYPE_PASS_24(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_23(provider_type, __VA_ARGS__))
#define TYPE_PASS_25(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_24(provider_type, __VA_ARGS__))
#define TYPE_PASS_26(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_25(provider_type, __VA_ARGS__))
#define TYPE_PASS_27(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_26(provider_type, __VA_ARGS__))
#define TYPE_PASS_28(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_27(provider_type, __VA_ARGS__))
#define TYPE_PASS_29(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_28(provider_type, __VA_ARGS__))
#define TYPE_PASS_30(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_29(provider_type, __VA_ARGS__))
#define TYPE_PASS_31(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_30(provider_type, __VA_ARGS__))
#define TYPE_PASS_32(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_31(provider_type, __VA_ARGS__))
#define TYPE_PASS_33(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_32(provider_type, __VA_ARGS__))
#define TYPE_PASS_34(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_33(provider_type, __VA_ARGS__))
#define TYPE_PASS_35(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_34(provider_type, __VA_ARGS__))
#define TYPE_PASS_36(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_35(provider_type, __VA_ARGS__))
#define TYPE_PASS_37(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_36(provider_type, __VA_ARGS__))
#define TYPE_PASS_38(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_37(provider_type, __VA_ARGS__))
#define TYPE_PASS_39(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_38(provider_type, __VA_ARGS__))
#define TYPE_PASS_40(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_39(provider_type, __VA_ARGS__))
#define TYPE_PASS_41(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_40(provider_type, __VA_ARGS__))
#define TYPE_PASS_42(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_41(provider_type, __VA_ARGS__))
#define TYPE_PASS_43(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_42(provider_type, __VA_ARGS__))
#define TYPE_PASS_44(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_43(provider_type, __VA_ARGS__))
#define TYPE_PASS_45(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_44(provider_type, __VA_ARGS__))
#define TYPE_PASS_46(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_45(provider_type, __VA_ARGS__))
#define TYPE_PASS_47(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_46(provider_type, __VA_ARGS__))
#define TYPE_PASS_48(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_47(provider_type, __VA_ARGS__))
#define TYPE_PASS_49(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_48(provider_type, __VA_ARGS__))
#define TYPE_PASS_50(provider_type, p1, ...) TYPE_PASS_1(provider_type, p1) EXPAND(TYPE_PASS_49(provider_type, __VA_ARGS__))

#define TYPE_PASS_0a() 
#define TYPE_PASS_1a(provider_type, p1) provider_type p1
#define TYPE_PASS_2a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_1a(provider_type, __VA_ARGS__))
#define TYPE_PASS_3a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_2a(provider_type, __VA_ARGS__))
#define TYPE_PASS_4a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_3a(provider_type, __VA_ARGS__))
#define TYPE_PASS_5a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_4a(provider_type, __VA_ARGS__))
#define TYPE_PASS_6a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_5a(provider_type, __VA_ARGS__))
#define TYPE_PASS_7a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_6a(provider_type, __VA_ARGS__))
#define TYPE_PASS_8a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_7a(provider_type, __VA_ARGS__))
#define TYPE_PASS_9a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_8a(provider_type, __VA_ARGS__))
#define TYPE_PASS_10a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_9a(provider_type, __VA_ARGS__))
#define TYPE_PASS_11a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_10a(provider_type, __VA_ARGS__))
#define TYPE_PASS_12a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_11a(provider_type, __VA_ARGS__))
#define TYPE_PASS_13a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_12a(provider_type, __VA_ARGS__))
#define TYPE_PASS_14a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_13a(provider_type, __VA_ARGS__))
#define TYPE_PASS_15a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_14a(provider_type, __VA_ARGS__))
#define TYPE_PASS_16a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_15a(provider_type, __VA_ARGS__))
#define TYPE_PASS_17a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_16a(provider_type, __VA_ARGS__))
#define TYPE_PASS_18a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_17a(provider_type, __VA_ARGS__))
#define TYPE_PASS_19a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_18a(provider_type, __VA_ARGS__))
#define TYPE_PASS_20a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_19a(provider_type, __VA_ARGS__))
#define TYPE_PASS_21a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_20a(provider_type, __VA_ARGS__))
#define TYPE_PASS_22a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_21a(provider_type, __VA_ARGS__))
#define TYPE_PASS_23a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_22a(provider_type, __VA_ARGS__))
#define TYPE_PASS_24a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_23a(provider_type, __VA_ARGS__))
#define TYPE_PASS_25a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_24a(provider_type, __VA_ARGS__))
#define TYPE_PASS_26a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_25a(provider_type, __VA_ARGS__))
#define TYPE_PASS_27a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_26a(provider_type, __VA_ARGS__))
#define TYPE_PASS_28a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_27a(provider_type, __VA_ARGS__))
#define TYPE_PASS_29a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_28a(provider_type, __VA_ARGS__))
#define TYPE_PASS_30a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_29a(provider_type, __VA_ARGS__))
#define TYPE_PASS_31a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_30a(provider_type, __VA_ARGS__))
#define TYPE_PASS_32a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_31a(provider_type, __VA_ARGS__))
#define TYPE_PASS_33a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_32a(provider_type, __VA_ARGS__))
#define TYPE_PASS_34a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_33a(provider_type, __VA_ARGS__))
#define TYPE_PASS_35a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_34a(provider_type, __VA_ARGS__))
#define TYPE_PASS_36a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_35a(provider_type, __VA_ARGS__))
#define TYPE_PASS_37a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_36a(provider_type, __VA_ARGS__))
#define TYPE_PASS_38a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_37a(provider_type, __VA_ARGS__))
#define TYPE_PASS_39a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_38a(provider_type, __VA_ARGS__))
#define TYPE_PASS_40a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_39a(provider_type, __VA_ARGS__))
#define TYPE_PASS_41a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_40a(provider_type, __VA_ARGS__))
#define TYPE_PASS_42a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_41a(provider_type, __VA_ARGS__))
#define TYPE_PASS_43a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_42a(provider_type, __VA_ARGS__))
#define TYPE_PASS_44a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_43a(provider_type, __VA_ARGS__))
#define TYPE_PASS_45a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_44a(provider_type, __VA_ARGS__))
#define TYPE_PASS_46a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_45a(provider_type, __VA_ARGS__))
#define TYPE_PASS_47a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_46a(provider_type, __VA_ARGS__))
#define TYPE_PASS_48a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_47a(provider_type, __VA_ARGS__))
#define TYPE_PASS_49a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_48a(provider_type, __VA_ARGS__))
#define TYPE_PASS_50a(provider_type, p1, ...) TYPE_PASS_1a(provider_type, p1) EXPAND(TYPE_PASS_49a(provider_type, __VA_ARGS__))


#define TYPE_PASS_0b() 
#define TYPE_PASS_1b(provider_type, p1) provider_type p1
#define TYPE_PASS_2b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_1b(provider_type, __VA_ARGS__))
#define TYPE_PASS_3b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_2b(provider_type, __VA_ARGS__))
#define TYPE_PASS_4b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_3b(provider_type, __VA_ARGS__))
#define TYPE_PASS_5b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_4b(provider_type, __VA_ARGS__))
#define TYPE_PASS_6b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_5b(provider_type, __VA_ARGS__))
#define TYPE_PASS_7b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_6b(provider_type, __VA_ARGS__))
#define TYPE_PASS_8b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_7b(provider_type, __VA_ARGS__))
#define TYPE_PASS_9b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_8b(provider_type, __VA_ARGS__))
#define TYPE_PASS_10b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_9b(provider_type, __VA_ARGS__))
#define TYPE_PASS_11b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_10b(provider_type, __VA_ARGS__))
#define TYPE_PASS_12b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_11b(provider_type, __VA_ARGS__))
#define TYPE_PASS_13b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_12b(provider_type, __VA_ARGS__))
#define TYPE_PASS_14b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_13b(provider_type, __VA_ARGS__))
#define TYPE_PASS_15b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_14b(provider_type, __VA_ARGS__))
#define TYPE_PASS_16b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_15b(provider_type, __VA_ARGS__))
#define TYPE_PASS_17b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_16b(provider_type, __VA_ARGS__))
#define TYPE_PASS_18b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_17b(provider_type, __VA_ARGS__))
#define TYPE_PASS_19b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_18b(provider_type, __VA_ARGS__))
#define TYPE_PASS_20b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_19b(provider_type, __VA_ARGS__))
#define TYPE_PASS_21b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_20b(provider_type, __VA_ARGS__))
#define TYPE_PASS_22b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_21b(provider_type, __VA_ARGS__))
#define TYPE_PASS_23b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_22b(provider_type, __VA_ARGS__))
#define TYPE_PASS_24b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_23b(provider_type, __VA_ARGS__))
#define TYPE_PASS_25b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_24b(provider_type, __VA_ARGS__))
#define TYPE_PASS_26b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_25b(provider_type, __VA_ARGS__))
#define TYPE_PASS_27b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_26b(provider_type, __VA_ARGS__))
#define TYPE_PASS_28b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_27b(provider_type, __VA_ARGS__))
#define TYPE_PASS_29b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_28b(provider_type, __VA_ARGS__))
#define TYPE_PASS_30b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_29b(provider_type, __VA_ARGS__))
#define TYPE_PASS_31b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_30b(provider_type, __VA_ARGS__))
#define TYPE_PASS_32b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_31b(provider_type, __VA_ARGS__))
#define TYPE_PASS_33b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_32b(provider_type, __VA_ARGS__))
#define TYPE_PASS_34b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_33b(provider_type, __VA_ARGS__))
#define TYPE_PASS_35b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_34b(provider_type, __VA_ARGS__))
#define TYPE_PASS_36b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_35b(provider_type, __VA_ARGS__))
#define TYPE_PASS_37b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_36b(provider_type, __VA_ARGS__))
#define TYPE_PASS_38b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_37b(provider_type, __VA_ARGS__))
#define TYPE_PASS_39b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_38b(provider_type, __VA_ARGS__))
#define TYPE_PASS_40b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_39b(provider_type, __VA_ARGS__))
#define TYPE_PASS_41b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_40b(provider_type, __VA_ARGS__))
#define TYPE_PASS_42b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_41b(provider_type, __VA_ARGS__))
#define TYPE_PASS_43b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_42b(provider_type, __VA_ARGS__))
#define TYPE_PASS_44b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_43b(provider_type, __VA_ARGS__))
#define TYPE_PASS_45b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_44b(provider_type, __VA_ARGS__))
#define TYPE_PASS_46b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_45b(provider_type, __VA_ARGS__))
#define TYPE_PASS_47b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_46b(provider_type, __VA_ARGS__))
#define TYPE_PASS_48b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_47b(provider_type, __VA_ARGS__))
#define TYPE_PASS_49b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_48b(provider_type, __VA_ARGS__))
#define TYPE_PASS_50b(provider_type, p1, ...) TYPE_PASS_1b(provider_type, p1) EXPAND(TYPE_PASS_49b(provider_type, __VA_ARGS__))

#define DEFINE_TYPE_PASS(where, ...) EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, TYPE_PASS_50, TYPE_PASS_49, TYPE_PASS_48, TYPE_PASS_47, TYPE_PASS_46, TYPE_PASS_45, TYPE_PASS_44, TYPE_PASS_43, TYPE_PASS_42, TYPE_PASS_41, TYPE_PASS_40, TYPE_PASS_39, TYPE_PASS_38, TYPE_PASS_37, TYPE_PASS_36, TYPE_PASS_35, TYPE_PASS_34, TYPE_PASS_33, TYPE_PASS_32, TYPE_PASS_31, TYPE_PASS_30, TYPE_PASS_29, TYPE_PASS_28, TYPE_PASS_27, TYPE_PASS_26, TYPE_PASS_25, TYPE_PASS_24, TYPE_PASS_23, TYPE_PASS_22, TYPE_PASS_21, TYPE_PASS_20, TYPE_PASS_19, TYPE_PASS_18, TYPE_PASS_17, TYPE_PASS_16, TYPE_PASS_15, TYPE_PASS_14, TYPE_PASS_13, TYPE_PASS_12, TYPE_PASS_11, TYPE_PASS_10, TYPE_PASS_9, TYPE_PASS_8, TYPE_PASS_7, TYPE_PASS_6, TYPE_PASS_5, TYPE_PASS_4, TYPE_PASS_3, TYPE_PASS_2, TYPE_PASS_1, TYPE_PASS_0))(where, __VA_ARGS__))
#define DEFINE_TYPE_PASS2(where, ...) EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, TYPE_PASS_50a, TYPE_PASS_49a, TYPE_PASS_48a, TYPE_PASS_47a, TYPE_PASS_46a, TYPE_PASS_45a, TYPE_PASS_44a, TYPE_PASS_43a, TYPE_PASS_42a, TYPE_PASS_41a, TYPE_PASS_40a, TYPE_PASS_39a, TYPE_PASS_38a, TYPE_PASS_37a, TYPE_PASS_36a, TYPE_PASS_35a, TYPE_PASS_34a, TYPE_PASS_33a, TYPE_PASS_32a, TYPE_PASS_31a, TYPE_PASS_30a, TYPE_PASS_29a, TYPE_PASS_28a, TYPE_PASS_27a, TYPE_PASS_26a, TYPE_PASS_25a, TYPE_PASS_24a, TYPE_PASS_23a, TYPE_PASS_22a, TYPE_PASS_21a, TYPE_PASS_20a, TYPE_PASS_19a, TYPE_PASS_18a, TYPE_PASS_17a, TYPE_PASS_16a, TYPE_PASS_15a, TYPE_PASS_14a, TYPE_PASS_13a, TYPE_PASS_12a, TYPE_PASS_11a, TYPE_PASS_10a, TYPE_PASS_9a, TYPE_PASS_8a, TYPE_PASS_7a, TYPE_PASS_6a, TYPE_PASS_5a, TYPE_PASS_4a, TYPE_PASS_3a, TYPE_PASS_2a, TYPE_PASS_1a, TYPE_PASS_0a))(where, __VA_ARGS__))
#define DEFINE_TYPE_PASS3(where, ...) EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, TYPE_PASS_50b, TYPE_PASS_49b, TYPE_PASS_48b, TYPE_PASS_47b, TYPE_PASS_46b, TYPE_PASS_45b, TYPE_PASS_44b, TYPE_PASS_43b, TYPE_PASS_42b, TYPE_PASS_41b, TYPE_PASS_40b, TYPE_PASS_39b, TYPE_PASS_38b, TYPE_PASS_37b, TYPE_PASS_36b, TYPE_PASS_35b, TYPE_PASS_34b, TYPE_PASS_33b, TYPE_PASS_32b, TYPE_PASS_31b, TYPE_PASS_30b, TYPE_PASS_29b, TYPE_PASS_28b, TYPE_PASS_27b, TYPE_PASS_26b, TYPE_PASS_25b, TYPE_PASS_24b, TYPE_PASS_23b, TYPE_PASS_22b, TYPE_PASS_21b, TYPE_PASS_20b, TYPE_PASS_19b, TYPE_PASS_18b, TYPE_PASS_17b, TYPE_PASS_16b, TYPE_PASS_15b, TYPE_PASS_14b, TYPE_PASS_13b, TYPE_PASS_12b, TYPE_PASS_11b, TYPE_PASS_10b, TYPE_PASS_9b, TYPE_PASS_8b, TYPE_PASS_7b, TYPE_PASS_6b, TYPE_PASS_5b, TYPE_PASS_4b, TYPE_PASS_3b, TYPE_PASS_2b, TYPE_PASS_1b, TYPE_PASS_0b))(where, __VA_ARGS__))

#define TYPE_MULTIPASS_0() 
#define TYPE_MULTIPASS_1(provider_type, p1) (provider_type p1)
#define TYPE_MULTIPASS_2(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_1(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_3(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_2(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_4(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_3(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_5(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_4(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_6(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_5(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_7(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_6(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_8(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_7(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_9(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_8(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_10(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_9(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_11(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_10(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_12(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_11(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_13(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_12(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_14(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_13(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_15(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_14(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_16(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_15(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_17(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_16(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_18(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_17(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_19(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_18(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_20(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_19(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_21(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_20(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_22(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_21(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_23(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_22(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_24(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_23(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_25(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_24(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_26(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_25(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_27(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_26(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_28(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_27(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_29(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_28(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_30(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_29(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_31(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_30(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_32(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_31(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_33(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_32(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_34(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_33(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_35(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_34(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_36(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_35(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_37(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_36(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_38(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_37(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_39(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_38(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_40(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_39(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_41(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_40(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_42(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_41(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_43(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_42(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_44(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_43(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_45(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_44(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_46(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_45(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_47(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_46(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_48(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_47(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_49(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_48(provider_type, __VA_ARGS__))
#define TYPE_MULTIPASS_50(provider_type, p1, ...) TYPE_MULTIPASS_1(provider_type, p1), EXPAND(TYPE_MULTIPASS_49(provider_type, __VA_ARGS__))

#define DEFINE_TYPE_MULTIPASS(where, transform, ...) where(EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, TYPE_MULTIPASS_50, TYPE_MULTIPASS_49, TYPE_MULTIPASS_48, TYPE_MULTIPASS_47, TYPE_MULTIPASS_46, TYPE_MULTIPASS_45, TYPE_MULTIPASS_44, TYPE_MULTIPASS_43, TYPE_MULTIPASS_42, TYPE_MULTIPASS_41, TYPE_MULTIPASS_40, TYPE_MULTIPASS_39, TYPE_MULTIPASS_38, TYPE_MULTIPASS_37, TYPE_MULTIPASS_36, TYPE_MULTIPASS_35, TYPE_MULTIPASS_34, TYPE_MULTIPASS_33, TYPE_MULTIPASS_32, TYPE_MULTIPASS_31, TYPE_MULTIPASS_30, TYPE_MULTIPASS_29, TYPE_MULTIPASS_28, TYPE_MULTIPASS_27, TYPE_MULTIPASS_26, TYPE_MULTIPASS_25, TYPE_MULTIPASS_24, TYPE_MULTIPASS_23, TYPE_MULTIPASS_22, TYPE_MULTIPASS_21, TYPE_MULTIPASS_20, TYPE_MULTIPASS_19, TYPE_MULTIPASS_18, TYPE_MULTIPASS_17, TYPE_MULTIPASS_16, TYPE_MULTIPASS_15, TYPE_MULTIPASS_14, TYPE_MULTIPASS_13, TYPE_MULTIPASS_12, TYPE_MULTIPASS_11, TYPE_MULTIPASS_10, TYPE_MULTIPASS_9, TYPE_MULTIPASS_8, TYPE_MULTIPASS_7, TYPE_MULTIPASS_6, TYPE_MULTIPASS_5, TYPE_MULTIPASS_4, TYPE_MULTIPASS_3, TYPE_MULTIPASS_2, TYPE_MULTIPASS_1, TYPE_MULTIPASS_0))(transform, __VA_ARGS__)))
#define DEFINE_TYPE_MULTIPASS_WITH_DEF_ARGS(where, args, transform, ...) where(EXPAND_MULTI args, EXPAND(EXPAND(_GET_NTH_ARG50(__VA_ARGS__, TYPE_MULTIPASS_50, TYPE_MULTIPASS_49, TYPE_MULTIPASS_48, TYPE_MULTIPASS_47, TYPE_MULTIPASS_46, TYPE_MULTIPASS_45, TYPE_MULTIPASS_44, TYPE_MULTIPASS_43, TYPE_MULTIPASS_42, TYPE_MULTIPASS_41, TYPE_MULTIPASS_40, TYPE_MULTIPASS_39, TYPE_MULTIPASS_38, TYPE_MULTIPASS_37, TYPE_MULTIPASS_36, TYPE_MULTIPASS_35, TYPE_MULTIPASS_34, TYPE_MULTIPASS_33, TYPE_MULTIPASS_32, TYPE_MULTIPASS_31, TYPE_MULTIPASS_30, TYPE_MULTIPASS_29, TYPE_MULTIPASS_28, TYPE_MULTIPASS_27, TYPE_MULTIPASS_26, TYPE_MULTIPASS_25, TYPE_MULTIPASS_24, TYPE_MULTIPASS_23, TYPE_MULTIPASS_22, TYPE_MULTIPASS_21, TYPE_MULTIPASS_20, TYPE_MULTIPASS_19, TYPE_MULTIPASS_18, TYPE_MULTIPASS_17, TYPE_MULTIPASS_16, TYPE_MULTIPASS_15, TYPE_MULTIPASS_14, TYPE_MULTIPASS_13, TYPE_MULTIPASS_12, TYPE_MULTIPASS_11, TYPE_MULTIPASS_10, TYPE_MULTIPASS_9, TYPE_MULTIPASS_8, TYPE_MULTIPASS_7, TYPE_MULTIPASS_6, TYPE_MULTIPASS_5, TYPE_MULTIPASS_4, TYPE_MULTIPASS_3, TYPE_MULTIPASS_2, TYPE_MULTIPASS_1, TYPE_MULTIPASS_0))(transform, __VA_ARGS__)))

#endif
