#ifndef GAME_COMPILER_OUTPUT_TYPE_STD
#define GAME_COMPILER_OUTPUT_TYPE_STD(...)
#endif


GAME_COMPILER_OUTPUT_TYPE_STD(game)
GAME_COMPILER_OUTPUT_TYPE_STD(editor)
GAME_COMPILER_OUTPUT_TYPE_STD(launcher)