#ifndef ENGINE_COMPONENT_STD
#define ENGINE_COMPONENT_STD(...)
#endif

ENGINE_COMPONENT_STD(config)
ENGINE_COMPONENT_STD(data_provider)
ENGINE_COMPONENT_STD(environment_info)
ENGINE_COMPONENT_STD(frame_notifier)
ENGINE_COMPONENT_STD(log_file_writer)
ENGINE_COMPONENT_STD(logger)
ENGINE_COMPONENT_STD(terminal_writer)

#undef ENGINE_COMPONENT_STD