#ifndef ENGINE_LOGGER_MODULE_STD
#define ENGINE_LOGGER_MODULE_STD(...)
#endif

#ifndef ENGINE_LOGGER_LEVEL_STD
#define ENGINE_LOGGER_LEVEL_STD(...)
#endif

#ifndef ENGINE_LOGGER_ITEM_PART_STD
#define ENGINE_LOGGER_ITEM_PART_STD(...)
#endif

ENGINE_LOGGER_MODULE_STD(core)

ENGINE_LOGGER_LEVEL_STD(task_started)
ENGINE_LOGGER_LEVEL_STD(task_failed)
ENGINE_LOGGER_LEVEL_STD(task_done)
ENGINE_LOGGER_LEVEL_STD(message)
ENGINE_LOGGER_LEVEL_STD(warning)
ENGINE_LOGGER_LEVEL_STD(error)


#undef ENGINE_LOGGER_ITEM_PART_STD
#undef ENGINE_LOGGER_LEVEL_STD
#undef ENGINE_LOGGER_MODULE_STD