#ifndef ENGINE_TASK_THREAD_CALLER_STD
#define ENGINE_TASK_THREAD_CALLER_STD(...)
#endif

#ifndef ENGINE_TASK_THREAD_CALLER_CUSTOM_STD
#define ENGINE_TASK_THREAD_CALLER_CUSTOM_STD(...)
#endif

ENGINE_TASK_THREAD_CALLER_STD(main)
ENGINE_TASK_THREAD_CALLER_STD(gui)
ENGINE_TASK_THREAD_CALLER_STD(renderer)
ENGINE_TASK_THREAD_CALLER_STD(update)
ENGINE_TASK_THREAD_CALLER_CUSTOM_STD(custom)


#undef ENGINE_TASK_THREAD_CALLER_CUSTOM_STD
#undef ENGINE_TASK_THREAD_CALLER_STD