#ifndef ENGINE_RICHTEXT_TAG_STD
#define ENGINE_RICHTEXT_TAG_STD(...)
#endif


ENGINE_RICHTEXT_TAG_STD(section_header)
ENGINE_RICHTEXT_TAG_STD(section_header_text)

ENGINE_RICHTEXT_TAG_STD(info)
ENGINE_RICHTEXT_TAG_STD(note)
ENGINE_RICHTEXT_TAG_STD(success)
ENGINE_RICHTEXT_TAG_STD(pending)
ENGINE_RICHTEXT_TAG_STD(warning)
ENGINE_RICHTEXT_TAG_STD(error)

ENGINE_RICHTEXT_TAG_STD(info_meta)
ENGINE_RICHTEXT_TAG_STD(note_meta)
ENGINE_RICHTEXT_TAG_STD(success_meta)
ENGINE_RICHTEXT_TAG_STD(pending_meta)
ENGINE_RICHTEXT_TAG_STD(warning_meta)
ENGINE_RICHTEXT_TAG_STD(error_meta)


#include "std/app_richtext_std.hpp"

#undef ENGINE_RICHTEXT_TAG_STD