#ifndef ENGINE_CONFIG_GLOBAL_STD
#define ENGINE_CONFIG_GLOBAL_STD(...)
#endif

#ifndef ENGINE_CONFIG_LOCAL_STD
#define ENGINE_CONFIG_LOCAL_STD(...)
#endif

#ifndef ENGINE_CONFIG_STD
#define ENGINE_CONFIG_STD(...)
#endif

ENGINE_CONFIG_STD(bool, has_terminal)

#undef ENGINE_CONFIG_STD
#undef ENGINE_CONFIG_LOCAL_STD
#undef ENGINE_CONFIG_GLOBAL_STD