#ifndef ENGINE_CONSOLE_OUTPUT_KIND_STD
#define ENGINE_CONSOLE_OUTPUT_KIND_STD(...)
#endif

#ifndef ENGINE_CONSOLE_OUTPUT_TAG_STD
#define ENGINE_CONSOLE_OUTPUT_TAG_STD(...)
#endif

#ifndef ENGINE_CONSOLE_SOURCE_STD
#define ENGINE_CONSOLE_SOURCE_STD(...)
#endif

#ifndef ENGINE_CONSOLE_MSG_TYPE_STD
#define ENGINE_CONSOLE_MSG_TYPE_STD(...)
#endif

#ifndef ENGINE_CONSOLE_META_TYPE_STD
#define ENGINE_CONSOLE_META_TYPE_STD(...)
#endif

ENGINE_CONSOLE_OUTPUT_KIND_STD(meta)
ENGINE_CONSOLE_OUTPUT_KIND_STD(note)
ENGINE_CONSOLE_OUTPUT_KIND_STD(info)
ENGINE_CONSOLE_OUTPUT_KIND_STD(pending)
ENGINE_CONSOLE_OUTPUT_KIND_STD(success)
ENGINE_CONSOLE_OUTPUT_KIND_STD(failure)
ENGINE_CONSOLE_OUTPUT_KIND_STD(warning)
ENGINE_CONSOLE_OUTPUT_KIND_STD(error)

ENGINE_CONSOLE_OUTPUT_TAG_STD(meta)

ENGINE_CONSOLE_SOURCE_STD(core)
ENGINE_CONSOLE_SOURCE_STD(user_input)
ENGINE_CONSOLE_SOURCE_STD(user_result)

ENGINE_CONSOLE_MSG_TYPE_STD(meta)
ENGINE_CONSOLE_MSG_TYPE_STD(logger)
ENGINE_CONSOLE_MSG_TYPE_STD(environment_info)

ENGINE_CONSOLE_META_TYPE_STD(output_start)
ENGINE_CONSOLE_META_TYPE_STD(output_end)

#undef ENGINE_CONSOLE_META_TYPE_STD
#undef ENGINE_CONSOLE_MSG_TYPE_STD
#undef ENGINE_CONSOLE_SOURCE_STD
#undef ENGINE_CONSOLE_OUTPUT_TAG_STD
#undef ENGINE_CONSOLE_OUTPUT_KIND_STD