#ifndef ENGINE_ENVIRONMENT_INFO_STD
#define ENGINE_ENVIRONMENT_INFO_STD(...)
#endif

#ifndef ENGINE_ENVIRONMENT_INFO_STATUS_STD
#define ENGINE_ENVIRONMENT_INFO_STATUS_STD(...)
#endif

ENGINE_ENVIRONMENT_INFO_STD(engine_version, "Engine version"_u)
ENGINE_ENVIRONMENT_INFO_STD(launched_time, "Launched at"_u)
ENGINE_ENVIRONMENT_INFO_STD(os_name, "OS"_u)
ENGINE_ENVIRONMENT_INFO_STD(os_ver, "OS version"_u)
ENGINE_ENVIRONMENT_INFO_STD(cpu_cores, "CPU cores"_u)
ENGINE_ENVIRONMENT_INFO_STD(cpu_cache_line, "CPU cache line size"_u)
ENGINE_ENVIRONMENT_INFO_STD(cpu_features, "CPU features"_u)


ENGINE_ENVIRONMENT_INFO_STATUS_STD(not_yet_populated)
ENGINE_ENVIRONMENT_INFO_STATUS_STD(normal)
ENGINE_ENVIRONMENT_INFO_STATUS_STD(good)
ENGINE_ENVIRONMENT_INFO_STATUS_STD(bad)

#undef ENGINE_ENVIRONMENT_INFO_STATUS_STD
#undef ENGINE_ENVIRONMENT_INFO_STD