#ifndef ENGINE_MESSENGER_QUEUE_STD
#define ENGINE_MESSENGER_QUEUE_STD(...)
#endif

#ifndef ENGINE_MESSENGER_MSG_BASE_TYPE_STD
#define ENGINE_MESSENGER_MSG_BASE_TYPE_STD(...)
#endif

ENGINE_MESSENGER_QUEUE_STD(console)

ENGINE_MESSENGER_MSG_BASE_TYPE_STD(msg)
ENGINE_MESSENGER_MSG_BASE_TYPE_STD(register_instance)
ENGINE_MESSENGER_MSG_BASE_TYPE_STD(unregister_instance)

#undef ENGINE_MESSENGER_MSG_BASE_TYPE_STD
#undef ENGINE_MESSENGER_QUEUE_STD