#ifndef ENGINE_TASK_THREAD_CALLER_STD
#define ENGINE_TASK_THREAD_CALLER_STD(...)
#endif

ENGINE_TASK_THREAD_CALLER_STD(core)
ENGINE_TASK_THREAD_CALLER_STD(gui)
ENGINE_TASK_THREAD_CALLER_STD(renderer)
ENGINE_TASK_THREAD_CALLER_STD(update)


#undef ENGINE_TASK_THREAD_CALLER_STD